spring:
  application:
    name: condominium
  data:
    mongodb:
      uri: mongodb+srv://condominium:62DC9G8V4RlAwqOX@condominium.qfgszpm.mongodb.net/condominio
      database: condominio

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

condominium:
  cashFundPercentage: 10

jjwt:
  secret: $2y$10$3cqgDPY2IdFj7ftsKI5O9eiQed72JvDUib761rAOTB0CTbkxgLCV2
  expiration: 2700